server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: ${APPLICATION_NAME:spring-cloud-eureka}
  # eureka 相关配置
  security:
    user:
      name: ${EUREKA_ADMIN_NAME:eureka}
      password: ${EUREKA_ADMIN_PASSWORD:eureka}

# eureka 相关配置
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 30000
  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    prefer-ip-address: ${PREFER_IP_ADDRESS:false}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: ${FETCH_REGISTRY:false}
    register-with-eureka: ${REGISTER_WITH_EUREKA:false}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/}

# actuator 相关配置
management:
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS:info,shutdown}
  endpoint:
    shutdown:
      enabled: ${ENABLE_SHOWDOWN:false}