version: "3"
services:

  # 定义一个名为 spring-cloud-eureka-master 的服务
  spring-cloud-eureka-master:
    # 指定容器所使用的镜像名称为 spring-cloud-eureka
    image: spring-cloud-eureka:latest
    # 指定容器的名称为 spring-cloud-eureka-master
    container_name: spring-cloud-eureka-master
    privileged: false
    # 设置容器的自动重启策略为 always，即容器总是重新启动
    restart: always
    build:
      # 指定构建该服务的上下文路径，即 docker-compose.yml 所在的目录
      context: ./
      # 指定 Dockerfile 文件路径
      dockerfile: ./spring-cloud-eureka/Dockerfile
      # 参数
      args:
        VERSION: 1.1.0
    # 暴露容器的端口映射，将容器的端口映射到主机端口
    ports:
      - "8761:8761"
    # 启动环境参数配置
    environment:
      - SERVER_PORT=8761
      - APPLICATION_NAME=spring-cloud-eureka
      - EUREKA_ADMIN_NAME=admin
      - EUREKA_ADMIN_PASSWORD=123456
      - HOSTNAME=spring-cloud-eureka-master
      - PREFER_IP_ADDRESS=true
      - FETCH_REGISTRY=true
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://admin:123456@spring-cloud-eureka-slave:8762/eureka/
      - ENDPOINTS=info,shutdown
      - ENABLE_SHOWDOWN=true
      - ENABLE_SELF_PRESERVATION=true
      - EVICTION_INTERVAL_TIMER_IN_MS=30000
    networks:
      - tsai-spring-cloud

  # 定义一个名为 spring-cloud-eureka-slave 的服务
  spring-cloud-eureka-slave:
    # 指定容器所使用的镜像名称为 spring-cloud-eureka
    image: spring-cloud-eureka:latest
    # 指定容器的名称为 spring-cloud-eureka-master
    container_name: spring-cloud-eureka-slave
    privileged: false
    # 设置容器的自动重启策略为 always，即容器总是重新启动
    restart: always
    build:
      # 指定构建该服务的上下文路径，即 docker-compose.yml 所在的目录
      context: ./
      # 指定 Dockerfile 文件路径
      dockerfile: ./spring-cloud-eureka/Dockerfile
      # 参数
      args:
        VERSION: 1.1.0
    # 暴露容器的端口映射，将容器的端口映射到主机端口
    ports:
      - "8762:8762"
    # 启动环境参数配置
    environment:
      - SERVER_PORT=8762
      - APPLICATION_NAME=spring-cloud-eureka
      - EUREKA_ADMIN_NAME=admin
      - EUREKA_ADMIN_PASSWORD=123456
      - HOSTNAME=spring-cloud-eureka-slave
      - PREFER_IP_ADDRESS=true
      - FETCH_REGISTRY=true
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://admin:123456@spring-cloud-eureka-master:8761/eureka/
      - ENDPOINTS=info,shutdown
      - ENABLE_SHOWDOWN=true
      - ENABLE_SELF_PRESERVATION=true
      - EVICTION_INTERVAL_TIMER_IN_MS=30000
    networks:
      - tsai-spring-cloud


networks:
  tsai-spring-cloud:
    driver: bridge